### ISSUE TITLE
layout components

### ISSUE THREAD

**Issue by freeman-lab** [carbonplan/components#110]
To capture a quick conversation with @katamartin , we discussed a plan for creating a new family of components related to layouts. We're now finding ourselves reusing certain layout-related patterns across different sites (maps, docs, research), and it could be good to clean them up and organize them.

We agreed they feel sufficiently related to one another and distinct from the more generic current `components` that we liked the idea of a separate repo. We also specifically liked the idea of using tree-shakable hierarchies, so we could organize them as:

```
import { Article } from '@carbonplan/layouts/research'
import { Heading } from '@carbonplan/layouts/research'
import { References } from '@carbonplan/layouts/research'
import { Tool } from '@carbonplan/layouts/research'

import { Section } from '@carbonplan/layouts/docs'
import { Sidenav } from '@carbonplan/layouts/docs'

import { Section } from '@carbonplan/layouts/map'
import { ControlPanel } from '@carbonplan/layouts/map'
```

I think our goal would be to only do this for layouts that get reused across multiple repos. Will take some work structuring the repo / package appropriately, but feels worthwhile!

**Comment by freeman-lab** [comment]
Work now started at https://github.com/carbonplan/layouts

**Comment by katamartin** [comment]
Closing this out now that we're using `@carbonplan/layouts` in production!
